---

# Copyright (c) 2018 Hexanode
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# Install HAProxy package from debian stable repository
- name: Install required HAProxy package
  apt:
    name: haproxy
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 86400

- name: Ensure HAProxy is started and enabled at boot
  service:
    name: haproxy
    state: started
    enabled: yes
