---

# Copyright (c) 2018 Hexanode
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# OS support verification
- name: Check OS support
  fail:
    msg: "Unsupported OS for haproxy role. Currently supported : Debian 8 to 10"
  when: >
    (ansible_distribution != 'Debian')
    or
    (ansible_distribution == 'Debian' and (ansible_distribution_major_version is version('8', '<') or ansible_distribution_major_version is version('10', '>')))

# Install
- name: Static import of install
  import_tasks: install.yml
  tags: haproxy_install

# SSL
- name: Static import of ssl
  import_tasks: ssl.yml
  when: haproxy_generate_self_signed_cert|bool
  tags: haproxy_ssl

# Config
- name: Static import of config
  import_tasks: config.yml
  tags: haproxy_config
