---

# Copyright (c) 2018 Kabolt
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# OS support verification
- name: Check OS support
  fail:
    msg: "Unsupported OS for docker role. Currently supported : Debian 9"
  when: ansible_os_family != "Debian" and ansible_distribution_major_version == "9"
  tags: always

# Install
- name: Static import of install
  import_tasks: install.yml
  tags: haproxy_install

# Deploy HAProxy configuration
- name: Deploy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: 'haproxy -c -f %s -q'
  notify: Reload HAProxy
  tags: haproxy_config

# Copy custom errors page
- name: Copy custom errors page
  copy:
    src: errors/
    dest: /etc/haproxy/errors/
    mode: 0644
  notify: Reload HAProxy
  when: haproxy_custom_errors_pages
  tags: haproxy_errors_pages
