---

# Copyright (c) 2018 Kabolt
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Create SSL directory
  file:
    path: /etc/haproxy/ssl
    state: directory
    mode: 0750

# This Require PyOpenSSL>=0.15
#
# - name: Generate a Self Signed OpenSSL certificate
#   openssl_certificate:
#     path: /etc/haproxy/ssl/self-signed.crt
#     privatekey_path: /etc/haproxy/ssl/self-signed.key
#     csr_path: /etc/haproxy/ssl/self-signed.csr
#     provider: selfsigned
#
# We use a simple way for now :
- name: Generate a Self Signed OpenSSL certificate
  shell: openssl req -x509 -newkey rsa:4096 -keyout selfsigned.key -out selfsigned.crt -days 365 -nodes -subj '/CN=selfsigned' && cat selfsigned.crt selfsigned.key > selfsigned.pem
  args:
    chdir: /etc/haproxy/ssl/
    creates: selfsigned.pem
