---

- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted

- name: Reload HAProxy
  service:
    name: haproxy
    state: reloaded

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
